### ISSUE TITLE
Background

### ISSUE THREAD

**Issue by arokem** [Brainhack-Proceedings-2015/Pfan_HBM_SOBF#6]
With apologies for the break, a couple more comments regarding the content:
1. It is not clear from the introduction whether this project is a novel application of these methods to this question, or an implementation of the. It would help to clarify what systems have been previously modeled using the SH equations, and conversely what models have been previously offered for columnar organization in cortex (just a bit, not an exhaustive lit review!). 
2. A bit of clarification around your pseudo-code would be useful. For example, which of your variables corresponds to $\Lambda$. I assume it's `L`? What does `Q` stand for?

**Comment by pfannmoe** [comment]
Dear arokem,

I was offline for a while. I am very sorry for that. Point 1 is now clarified as far as possible without introducing new literature. Point 2 posed a bit more problems. This was due to the relatively complex procedure for the numerical solution of the equation. The equation is solved by computation of the change per time step in Fourier space. Therefore, a Taylor expansion of the equation is carried out and periodic boundary conditions are applied. In text books the discussion, which allows to understand the derived properties, takes several pages. Unfortunately, a simple guiding explanation in terms of lambda and epsilon is not possible. However, that can be done for the equation itself. It seemed to me as if it was sufficient to show the equation including the parameters and to explain how it was solved. Do you think that this is allright?

Yours pfannmoe

**Comment by arokem** [comment]
OK. Would be nice to say where you got the open source script that you modified for this (a link to the original code would suffice).

**Comment by pfannmoe** [comment]
Dear arokem,

the link is now included. You can also find it in the script that is included in the repository.

Yours Joerg

**Comment by arokem** [comment]
Cool. Looks good to me. Closing this issue.
